#ifndef __GLOBAL_H_
#define __GLOBAL_H_

#define COLOR__RANDOM() (rand() % 8 + 30)
#define COLOR__BLACK 30
#define COLOR__RED 31
#define COLOR__GREEN 32
#define COLOR__YELLOW 33
#define COLOR__BLUE 34
#define COLOR__PURPLE 35
#define COLOR__SKY_BLUE 36
#define COLOR__WHITE 37

#define VIEW_WIDTH 120
#define VIEW_HEADER_HEIGHT 4 // must be even
#define VIEW_MAIN_HEIGHT 74 // must be even

#define KEYCONF__TERMINATE_PROCESS 'q'
#define KEYCONF__BEGIN_GAME 's'
#define KEYCONF__BEGIN_AUTOMATIC_GAME 'a'
#define KEYCONF__GAME_END_BACK_TO_HOMEPAGE 'h'
#define KEYCONF__GAME_END_RESTART 'r'
#define KEYCONF__GAME_END_RESTART_AUTOMATIC_GAME 'a'
#define KEYCONF__IN_GAME__JUMP ' ' // space

#define GAMECONF__MAX_JUMP_DISTANCE_BY_XY 64
#define GAMECONF__MIN_JUMP_DISTANCE_BY_XY 2
#define GAMECONF__JUMP_HOLD_CHECK_INTERVAL 100
#define GAMECONF__JUMP_ADD_DISTANCE_PER_HOLD_CHECK 4

// 120 * 185
#define GAMEPOS__CHESS_HEIGHT 17
#define GAMEPOS__CHESS_MIN_COMPRESSED_HEIGHT 5
#define GAMEPOS__CHESS_RADIUS 1
#define GAMEPOS__CHESS_ANCHOR_LEFT_X 30
#define GAMEPOS__CHESS_ANCHOR_LEFT_Y 130
#define GAMEPOS__CHESS_ANCHOR_RIGHT_X 85 // 50
#define GAMEPOS__CHESS_ANCHOR_RIGHT_Y 130
#define GAMEPOS__DEFAULT_STAGE_ANCHOR_X GAMEPOS__CHESS_ANCHOR_LEFT_X
#define GAMEPOS__DEFAULT_STAGE_ANCHOR_Y GAMEPOS__CHESS_ANCHOR_LEFT_Y
#define GAMEPOS__DEFAULT_STAGE_RADIUS 16
#define GAMEPOS__MIN_STAGE_RADIUS 6
#define GAMEPOS__STAGE_HEIGHT 14
#define GAMEPOS__STAGE_MIN_COMPRESSED_HEIGHT 10

#define GAMEPOS_TO_VIEW__SCALE_Y_VALUE (0.4f)
#define GAMEPOS_TO_VIEW__SCALE_Y_FN(y) (int)((float)(y) * GAMEPOS_TO_VIEW__SCALE_Y_VALUE + 0.5f)

#define ANIMATION__GAMEPAGE_JUMP_FRAMES_CNT 6
#define ANIMATION__GAMEPAGE_JUMP_LAST_MILLISECOND 450
#define ANIMATION__GAMEPAGE_MOVE_FRAMES_CNT 8
#define ANIMATION__GAMEPAGE_MOVE_LAST_MILLISECOND 4
#define ANIMATION__GAMEPAGE_FALL_FRAMES_CNT 3
#define ANIMATION__GAMEPAGE_FALL_LAST_MILLISECOND 300

#endif /* __GLOBAL_H_ */
